routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('subjects', SubjectController::class);
Route::resource('questions', QuestionController::class);

Route::get('exam/create/1', [QuestionController::class, 'createExam'])->name('generateExam');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Question extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $fillable = ['subject_id', 'question', 'level'];

    public function subject(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Subject::class);
    }

    public function points(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(QuestionPoint::class)->with('options');
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use App\Models\QuestionPoint;
use App\Models\QuestionPointOption;
use App\Models\Subject;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use PhpOffice\PhpWord\Exception\Exception;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;
use File;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|\Illuminate\Foundation\Application|\Illuminate\View\View|View
     */
    public function index()
    {
        $questions = Question::with(['subject','points'])->get();
        return view('question.index',compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|\Illuminate\Foundation\Application|\Illuminate\View\View|View
     */
    public function create()
    {
        $subjects = Subject::all();
        return view('question.create',compact('subjects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {

        $request->validate([
            'subject' => 'required|exists:App\Models\Subject,id',
            'question' => 'required',
            'level' => 'required', Rule::in(['hard', 'medium', 'easy']),
            'points' => 'required|array',
        ]);
        $question = Question::create([
            'subject_id' => $request->subject,
            'question' => $request->question,
            'level' => $request->level,
        ]);

        $optionsOrder = [0 => 'A', 1 => 'B', 2 => 'C', 3 => 'D'];
        for ($x = 1; $x <= 3; $x++) {
            $questionPoint = QuestionPoint::create([
                'question_id' => $question->id,
                'point' => $request->points[$x]['point'],
                'order' => $x,
                'answer' => $request->points[$x]['Answer'],
            ]);
            for ($y = 0; $y <= 3; $y++) {
                QuestionPointOption::create([
                    'questionPoint_id' => $questionPoint->id,
                    'option' => $request->points[$x]['options'][$optionsOrder[$y]],
                    'order' => $optionsOrder[$y],
                ]);
            }
        }
        return redirect()->route('questions.index')->with('success','Question created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param Question $question
     * @return Application|Factory|\Illuminate\Foundation\Application|\Illuminate\View\View|View
     */
    public function show(Question $question)
    {
        return view('question.show',compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Question $question
     * @return Application|Factory|\Illuminate\Foundation\Application|\Illuminate\View\View|View
     */
    public function edit($question_id)
    {
        $question = Question::where('id', $question_id)->with(['subject', 'points'])->first();
        $subjects = Subject::all();
        return view('question.edit',compact('question', 'subjects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Question $question
     * @return RedirectResponse
     */
    public function update(Request $request, Question $question): RedirectResponse
    {
        $request->validate([
            'subject' => 'required|exists:App\Models\Subject,id',
            'question' => 'required',
            'level' => 'required', Rule::in(['hard', 'medium', 'easy']),
        ]);
//        return $request->all();
        $question->update([
            'subject_id' => $request->subject,
            'question' => $request->question,
            'level' => $request->level,
        ]);

        $optionsOrder = [0 => 'A', 1 => 'B', 2 => 'C', 3 => 'D'];
        for ($x = 1; $x <= 3; $x++) {
            $questionPoint = QuestionPoint::where('id')->update([
                'question_id' => $question->id,
                'point' => $request->points[$x]['point'],
                'order' => $x,
                'answer' => $request->points[$x]['Answer'],
            ]);
        }
        $optionsOrder = [0 => 'A', 1 => 'B', 2 => 'C', 3 => 'D'];
        for ($x = 1; $x <= 3; $x++) {
            $questionPoint = QuestionPoint::where('id', $request->points[$x]['id'])->update([
                'point' => $request->points[$x]['point'],
                'answer' => $request->points[$x]['Answer'],
            ]);
            for ($y = 0; $y <= 3; $y++) {
                QuestionPointOption::where('id', $request->points[$x]['options'][$optionsOrder[$y]]['id'])->update([
                    'option' => $request->points[$x]['options'][$optionsOrder[$y]]['option'],
                ]);
            }
        }
        return redirect()->route('questions.index')
            ->with('success','Question updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Question $question
     * @return RedirectResponse
     */
    public function destroy(Question $question): RedirectResponse
    {
        $question->delete();

        return redirect()->route('questions.index')
            ->with('success','Question deleted successfully');
    }

    /**
     * @throws Exception
     */
    public function createExam(): \Symfony\Component\HttpFoundation\BinaryFileResponse
    {
        $examQuestions[] = Question::where('subject_id', 1)->where('level', 'easy')->inRandomOrder()->limit(1)->with('points')->first();
        $examQuestions[] = Question::where('subject_id', 1)->where('level', 'medium')->inRandomOrder()->limit(1)->with('points')->first();
        $examQuestions[] = Question::where('subject_id', 1)->where('level', 'hard')->inRandomOrder()->limit(1)->with('points')->first();

        $phpWord = new PhpWord();
        $section = $phpWord->addSection();

        $order = [0 => 'First', 1 => 'Second', 2 => 'Third'];
        foreach ($examQuestions as $key => $question){
            $section->addText(
                $order[$key] . ' ' . $question->question
            );
            foreach ($question['points'] as $point){
                $section->addText(
                     $point->order . '- ' . $point->point . '
                     '
                );
                foreach ($point['options'] as $option){
                    $section->addText(
                        $option->order . '- ' . $option->option . '
                        '
                    );
                }
                $section->addText('');
            }
        }
        $exams = count(File::files(public_path() . '/exams'));
        $objWriter = IOFactory::createWriter($phpWord, 'ODText');
        $objWriter->save('exams/exam' . ($exams + 1) . '.odt');
        return response()->download(public_path('exams/exam' . ($exams + 1) . '.odt'));
    }
}

resources/views/question/create.blade.php
@extends('layout.master')

@section('content')
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                    <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">questions</a></li>
                    <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Add New</li>
                </ol>
                <h6 class="font-weight-bolder mb-0">New question</h6>
            </nav>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body p-3">
                        <div class="row">
                            <form action='{{ route('questions.store') }}' method='Post'>
                                @csrf
                                <ul class="list-group">
                                    <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                                        <div class="mb-3 col-12">
                                            <label class="form-label" for="subject">Question`s Subject</label>
                                            <select class="form-select" name="subject" id="subject" aria-label="Default select example" required>
                                                <option selected>Select Subject</option>
                                                @foreach($subjects as $subject)
                                                    <option value="{{ $subject['id'] }}">{{ $subject['name'] }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </li>
                                    <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                                        <div class="mb-3 col-12">
                                            <div class="content">
                                                <label class="form-label" for="question">Question Title</label>
                                                <input class="form-control" name="question" id="question" type="text" placeholder="Question Title" required>
                                            </div><br>
                                            <div class="content">
                                                <label class="form-label" for="QuestionLevel">Question level</label>
                                                <select class="form-select" name="level" id="QuestionLevel" aria-label="Default select example" required>
                                                    <option value="easy" selected>Easy</option>
                                                    <option value="medium">Medium</option>
                                                    <option value="hard">hard</option>
                                                </select>
                                            </div>
                                        </div>
                                    </li>
                                    @for ($i = 1; $i <= 3; $i++)
                                        <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                                            <div class="mb-3 col-12">
                                                <div class="content">
                                                    <h4>Point {{$i}}</h4>
                                                </div><br>
                                                <div class="content">
                                                    <label class="form-label" for="point{{$i}}Question">Point {{ $i }} Question</label>
                                                    <textarea class="form-control" name="points[{{$i}}][point]" id="point{{$i}}Question" rows="3" required></textarea>
                                                </div><br>
                                                <div class="content">
                                                    <div class="row">
                                                        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                                                            <label class="form-label" for="point{{$i}}OptionA">option A</label>
                                                            <textarea class="form-control" name="points[{{$i}}][options][A]" id="point{{$i}}OptionA" rows="3" required></textarea>
                                                        </div>
                                                        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                                                            <label class="form-label" for="point{{$i}}OptionB">option B</label>
                                                            <textarea class="form-control" name="points[{{$i}}][options][B]" id="point{{$i}}OptionB" rows="3" required></textarea>
                                                        </div>
                                                        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                                                            <label class="form-label" for="point{{$i}}OptionC">option C</label>
                                                            <textarea class="form-control" name="points[{{$i}}][options][C]" id="point{{$i}}OptionC" rows="3" required></textarea>
                                                        </div>
                                                        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                                                            <label class="form-label" for="point{{$i}}OptionD">option D</label>
                                                            <textarea class="form-control" name="points[{{$i}}][options][D]" id="point{{$i}}OptionD" rows="3" required></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="content">
                                                    <label class="form-label" for="Answer">Answer</label>
                                                    <select class="form-select" name="points[{{$i}}][Answer]" id="Answer" aria-label="Default select example" required>
                                                        <option value="A" selected>A</option>
                                                        <option value="B">B</option>
                                                        <option value="C">C</option>
                                                        <option value="D">D</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </li>
                                    @endfor
                                    <li>
                                        <div class="card-header pb-0 p-3">
                                            <div class="row">
                                                <div class="col-6 text-end">
                                                    <button type="submit" class="btn bg-gradient-dark mb-0" href="javascript:;">
                                                        <i class="fas fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;Save Question
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/question/edit.blade.php
@extends('layout.master')

@section('content')
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                    <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">questions</a></li>
                    <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Edit</li>
                </ol>
                <h6 class="font-weight-bolder mb-0">Edit Question</h6>
            </nav>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body p-3">
                        <div class="row">
                            <form action='{{ route('questions.update', $question->id) }}' method='POST'>
                                @csrf
                                @method('PUT')
                                <ul class="list-group">
                                    <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                                        <div class="mb-3 col-12">
                                            <label class="form-label" for="subject">Question`s Subject</label>
                                            <select class="form-select" name="subject" id="subject" aria-label="Default select example" required>
                                                @foreach($subjects as $subject)
                                                    <option value="{{ $subject['id'] }}" {{ ($question['subject_id'] == $subject['id']) ? 'selected' : '' }}>
                                                        {{ $subject['name'] }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </li>
                                    <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                                        <div class="mb-3 col-12">
                                            <div class="content">
                                                <label class="form-label" for="question">Question Title</label>
                                                <input class="form-control" name="question" id="question" type="text" value="{{ $question['question'] }}"
                                                       placeholder="Question Title" required>
                                            </div><br>
                                            <div class="content">
                                                <label class="form-label" for="QuestionLevel">Question level</label>
                                                <select class="form-select" name="level" id="QuestionLevel" aria-label="Default select example" required>
                                                    <option value="easy" {{ ($question['level'] == 'easy') ? 'selected' : '' }}>Easy</option>
                                                    <option value="medium" {{ ($question['level'] == 'medium') ? 'selected' : '' }}>Medium</option>
                                                    <option value="hard" {{ ($question['level'] == 'hard') ? 'selected' : '' }}>hard</option>
                                                </select>
                                            </div>
                                        </div>
                                    </li>
                                    @foreach ($question['points'] as $key => $point)
                                        <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                                            <div class="mb-3 col-12">
                                                <div class="content">
                                                    <h4>Point {{ $point['order'] }}</h4>
                                                </div><br>
                                                <div class="content">
                                                    <label class="form-label" for="point{{ $point['order'] }}Question">Point {{ $point['order'] }} Question</label>
                                                    <textarea class="form-control" name="points[{{ $point['order'] }}][point]" id="point{{ $point['order'] }}Question" rows="3" required>{{ $point['point'] }}</textarea>
                                                </div><br>
                                                <div class="content">
                                                    <div class="row">
                                                        @foreach($point['options'] as $option)
                                                            <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
                                                                <label class="form-label" for="point{{ $point['order'] }}Option{{ $option['order'] }}">option {{ $option['order'] }}</label>
                                                                <textarea class="form-control" name="points[{{ $point['order'] }}][options][{{ $option['order'] }}][option]"
                                                                          id="point{{ $point['order'] }}Option{{ $option['order'] }}" rows="3" required>{{ $option['option'] }}</textarea>
                                                            </div>
                                                            <input type="hidden" name="points[{{ $point['order'] }}][options][{{ $option['order'] }}][id]" value="{{ $option['id'] }}">
                                                        @endforeach
                                                    </div>
                                                </div>
                                                <div class="content">
                                                    <label class="form-label" for="Answer">Answer</label>
                                                    <select class="form-select" name="points[{{ $point['order'] }}][Answer]" id="Answer" aria-label="Default select example" required>
                                                        <option value="A" {{ ($point['answer'] == 'A') ? 'selected' : '' }}>A</option>
                                                        <option value="B" {{ ($point['answer'] == 'B') ? 'selected' : '' }}>B</option>
                                                        <option value="C" {{ ($point['answer'] == 'C') ? 'selected' : '' }}>C</option>
                                                        <option value="D" {{ ($point['answer'] == 'D') ? 'selected' : '' }}>D</option>
                                                    </select>
                                                </div>
                                                <input type="hidden" name="points[{{ $point['order'] }}][id]" value="{{ $point['id'] }}">
                                            </div>
                                        </li>
                                    @endforeach
                                    <li>
                                        <div class="card-header pb-0 p-3">
                                            <div class="row">
                                                <div class="col-6 text-end">
                                                    <button type="submit" class="btn bg-gradient-dark mb-0" href="javascript:;">
                                                        <i class="fas fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;Save Question
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/question/index.blade.php
@extends('layout.master')

@section('content')
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                    <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">questions</a></li>
                    <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Questions List</li>
                </ol>
                <h6 class="font-weight-bolder mb-0">All questions</h6>
            </nav>
            <div class="col-6 text-end">
                <a class="btn bg-gradient-dark mb-0" href="{{ route('generateExam') }}"><i class="fas fa-file-word" aria-hidden="true"></i>&nbsp;&nbsp;Generate Exam</a>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header pb-0 p-3">
                        <div class="row">
                            <div class="col-6 d-flex align-items-center">
                                <h6 class="mb-0">Questions</h6>
                            </div>
                            <div class="col-6 text-end">
                                <a class="btn btn-outline-primary btn-sm mb-0" href="{{ route('questions.create') }}">
                                    <i class="fas fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;Add New Question</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body px-0 pt-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center justify-content-center mb-0">
                                <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Question</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">level</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Subject</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Created At</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($questions as $question)
                                    <tr>
                                        <td>
                                            <div class="d-flex px-2">
                                                <div class="my-auto">
                                                    <h6 class="mb-0 text-sm">{{ $question->question }}</h6>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <p class="text-sm font-weight-bold mb-0">{{ $question->level }}</p>
                                        </td>
                                        <td>
                                            <span class="text-xs font-weight-bold">{{ $question->subject['name'] }}</span>
                                        </td>
                                        <td>
                                            <span class="text-xs font-weight-bold">{{ $question->created_at }}</span>
                                        </td>
                                        <td class="align-middle">
{{--                                            <button class="btn btn-link text-secondary mb-0">--}}
{{--                                                <i class="fa fa-ellipsis-v text-xs"></i>--}}
{{--                                            </button>--}}
                                            <form action="{{ route('questions.destroy', $question->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-link text-danger text-gradient px-3 mb-0" type="submit"><i class="far fa-trash-alt me-2" aria-hidden="true"></i>Delete</button>
                                            </form>
                                            <a class="btn btn-link text-dark px-3 mb-0" href="{{ route('questions.edit', $question->id) }}">
                                                <i class="fas fa-pencil-alt text-dark me-2" aria-hidden="true"></i>Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/question/show.blade.php
<?php